<?php declare(strict_types=1);

/*
 You may not change or alter any portion of this comment or credits
 of supporting developers from this source code or any supporting source code
 which is considered copyrighted (c) material of the original comment or credit authors.
*/

/**
 * @copyright 2000-2026 XOOPS Project (https://xoops.org)
 * @license   GNU GPL 2.0 or later (https://www.gnu.org/licenses/gpl-2.0.html)
 * @author    Michael Beck (mamba)
 */

require_once __DIR__ . '/preloads/autoloader.php';

$moduleDirName = basename(__DIR__);

$modversion = [];
$modversion['version']             = '1.6.0-Stable';
$modversion['module_status']       = '';
$modversion['release_date']        = '2026/07/23';
$modversion['name']                = _MI_MODULEINSTALLER_NAME;
$modversion['description']         = _MI_MODULEINSTALLER_DESC;
$modversion['author']              = 'Michael Beck';
$modversion['nickname']            = 'Mamba';
$modversion['credit']              = 'XOOPS Development Team';
$modversion['credits']             = 'XOOPS Development Team Credits';
$modversion['help']                = 'page=help';
$modversion['license']             = 'GNU GPL 2.0';
$modversion['license_url']         = 'www.gnu.org/licenses/gpl-2.0.html';
$modversion['official']            = 1; //1 indicates supported by XOOPS Dev Team, 0 means 3rd party supported
$modversion['image']               = 'assets/images/logoModule.png';
$modversion['dirname']             = basename(__DIR__);
$modversion['modicons16']          = 'assets/images/icons/16';
$modversion['modicons32']          = 'assets/images/icons/32';
$modversion['module_website_url']  = 'www.xoops.org/';
$modversion['module_website_name'] = 'XOOPS';
$modversion['min_php']             = '8.2';
$modversion['min_xoops']           = '2.5.12';
$modversion['min_admin']           = '1.2';
$modversion['min_db']              = ['mysql' => '5.5'];
$modversion['min_modules']         = ['mtools' => '1.2.0'];

// SQL Tables
// $modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
// $modversion['tables'][0] = 'installer';

// Scripts to run upon installation or update
$modversion['onInstall']   = 'include/oninstall.php';
$modversion['onUpdate']    = 'include/onupdate.php';
$modversion['onUninstall'] = 'include/onuninstall.php';

// Admin menu
$modversion['hasAdmin']   = 1;
$modversion['adminindex'] = 'admin/index.php';
$modversion['adminmenu']  = 'admin/menu.php';
$modversion['hasMain']    = 0;
// Set to 1 if you want to display menu generated by system module
$modversion['system_menu'] = 1;

// Search
$modversion['hasSearch'] = 0;

// Smarty
$modversion['use_smarty'] = 1;

// Preferences — sample data = sample module sets (see testdata/)
$modversion['config'][] = [
    'name'        => 'displaySampleButton',
    'title'       => '_CO_MODULEINSTALLER_SHOW_SAMPLE_BUTTON',
    'description' => '_CO_MODULEINSTALLER_SHOW_SAMPLE_BUTTON_DESC',
    'formtype'    => 'yesno',
    'valuetype'   => 'int',
    'default'     => 1,
];

